simu_name
simu_code_file
simu_comment
varied_simu_params
simu_param_dict
exp_dict
Traceback (most recent call last):
  File "/home/jdoelger/InfluenzaFitnessInference/code/notebooks/fitnessinference/analysis.py", line 2185, in <module>
    main()
  File "/home/jdoelger/InfluenzaFitnessInference/code/notebooks/fitnessinference/analysis.py", line 2153, in main
    exe_multi_simu_analysis_L(simu_name)
  File "/home/jdoelger/InfluenzaFitnessInference/code/notebooks/fitnessinference/analysis.py", line 923, in exe_multi_simu_analysis_L
    multi_simu_analysis(simu_name, ana_param_dict, varied_ana_params, exp_ana_dict)
  File "/home/jdoelger/InfluenzaFitnessInference/code/notebooks/fitnessinference/analysis.py", line 798, in multi_simu_analysis
    run_list = simu_dict['run_list']
KeyError: 'run_list'
